name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Core
          user: mrdvince
          config_timezone: Africa/Nairobi
          committer_message: "chore: update metrics"
          
          # Display
          template: classic
          base: header, activity, community, repositories
          
          plugin_isocalendar: yes
          
          plugin_languages: yes
          
          plugin_introduction: yes
          
          plugin_habits: yes
          
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          
          plugin_lines: yes
          
          plugin_activity: yes

          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_traffic: yes